// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2_shipping.proto

package s2.shipping;

/**
 * <pre>
 * Define the messages
 * </pre>
 *
 * Protobuf type {@code shipping.ShippingQtyRequest}
 */
public  final class ShippingQtyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:shipping.ShippingQtyRequest)
    ShippingQtyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShippingQtyRequest.newBuilder() to construct.
  private ShippingQtyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShippingQtyRequest() {
    productNo_ = "";
    shippingQty_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShippingQtyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            productNo_ = s;
            break;
          }
          case 16: {

            shippingQty_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return s2.shipping.ShippingImpl.internal_static_shipping_ShippingQtyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return s2.shipping.ShippingImpl.internal_static_shipping_ShippingQtyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            s2.shipping.ShippingQtyRequest.class, s2.shipping.ShippingQtyRequest.Builder.class);
  }

  public static final int PRODUCTNO_FIELD_NUMBER = 1;
  private volatile java.lang.Object productNo_;
  /**
   * <code>string productNo = 1;</code>
   */
  public java.lang.String getProductNo() {
    java.lang.Object ref = productNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productNo_ = s;
      return s;
    }
  }
  /**
   * <code>string productNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProductNoBytes() {
    java.lang.Object ref = productNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIPPINGQTY_FIELD_NUMBER = 2;
  private int shippingQty_;
  /**
   * <code>int32 shippingQty = 2;</code>
   */
  public int getShippingQty() {
    return shippingQty_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProductNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productNo_);
    }
    if (shippingQty_ != 0) {
      output.writeInt32(2, shippingQty_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProductNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productNo_);
    }
    if (shippingQty_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, shippingQty_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof s2.shipping.ShippingQtyRequest)) {
      return super.equals(obj);
    }
    s2.shipping.ShippingQtyRequest other = (s2.shipping.ShippingQtyRequest) obj;

    boolean result = true;
    result = result && getProductNo()
        .equals(other.getProductNo());
    result = result && (getShippingQty()
        == other.getShippingQty());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCTNO_FIELD_NUMBER;
    hash = (53 * hash) + getProductNo().hashCode();
    hash = (37 * hash) + SHIPPINGQTY_FIELD_NUMBER;
    hash = (53 * hash) + getShippingQty();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static s2.shipping.ShippingQtyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static s2.shipping.ShippingQtyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static s2.shipping.ShippingQtyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static s2.shipping.ShippingQtyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(s2.shipping.ShippingQtyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define the messages
   * </pre>
   *
   * Protobuf type {@code shipping.ShippingQtyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shipping.ShippingQtyRequest)
      s2.shipping.ShippingQtyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return s2.shipping.ShippingImpl.internal_static_shipping_ShippingQtyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return s2.shipping.ShippingImpl.internal_static_shipping_ShippingQtyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              s2.shipping.ShippingQtyRequest.class, s2.shipping.ShippingQtyRequest.Builder.class);
    }

    // Construct using s2.shipping.ShippingQtyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productNo_ = "";

      shippingQty_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return s2.shipping.ShippingImpl.internal_static_shipping_ShippingQtyRequest_descriptor;
    }

    @java.lang.Override
    public s2.shipping.ShippingQtyRequest getDefaultInstanceForType() {
      return s2.shipping.ShippingQtyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public s2.shipping.ShippingQtyRequest build() {
      s2.shipping.ShippingQtyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public s2.shipping.ShippingQtyRequest buildPartial() {
      s2.shipping.ShippingQtyRequest result = new s2.shipping.ShippingQtyRequest(this);
      result.productNo_ = productNo_;
      result.shippingQty_ = shippingQty_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof s2.shipping.ShippingQtyRequest) {
        return mergeFrom((s2.shipping.ShippingQtyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(s2.shipping.ShippingQtyRequest other) {
      if (other == s2.shipping.ShippingQtyRequest.getDefaultInstance()) return this;
      if (!other.getProductNo().isEmpty()) {
        productNo_ = other.productNo_;
        onChanged();
      }
      if (other.getShippingQty() != 0) {
        setShippingQty(other.getShippingQty());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      s2.shipping.ShippingQtyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (s2.shipping.ShippingQtyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object productNo_ = "";
    /**
     * <code>string productNo = 1;</code>
     */
    public java.lang.String getProductNo() {
      java.lang.Object ref = productNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductNoBytes() {
      java.lang.Object ref = productNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productNo = 1;</code>
     */
    public Builder setProductNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productNo = 1;</code>
     */
    public Builder clearProductNo() {
      
      productNo_ = getDefaultInstance().getProductNo();
      onChanged();
      return this;
    }
    /**
     * <code>string productNo = 1;</code>
     */
    public Builder setProductNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productNo_ = value;
      onChanged();
      return this;
    }

    private int shippingQty_ ;
    /**
     * <code>int32 shippingQty = 2;</code>
     */
    public int getShippingQty() {
      return shippingQty_;
    }
    /**
     * <code>int32 shippingQty = 2;</code>
     */
    public Builder setShippingQty(int value) {
      
      shippingQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 shippingQty = 2;</code>
     */
    public Builder clearShippingQty() {
      
      shippingQty_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:shipping.ShippingQtyRequest)
  }

  // @@protoc_insertion_point(class_scope:shipping.ShippingQtyRequest)
  private static final s2.shipping.ShippingQtyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new s2.shipping.ShippingQtyRequest();
  }

  public static s2.shipping.ShippingQtyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShippingQtyRequest>
      PARSER = new com.google.protobuf.AbstractParser<ShippingQtyRequest>() {
    @java.lang.Override
    public ShippingQtyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShippingQtyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShippingQtyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShippingQtyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public s2.shipping.ShippingQtyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

