// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2_shipping.proto

package s2.shipping;

public interface ShippingQtyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shipping.ShippingQtyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
