// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2_shipping.proto

package s2.shipping;

public interface ShippingQtyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shipping.ShippingQtyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>int32 shippingQty = 2;</code>
   */
  int getShippingQty();
}
