// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2_shipping.proto

package s2.shipping;

public interface updateLocRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shipping.updateLocRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productIndivNo = 1;</code>
   */
  java.lang.String getProductIndivNo();
  /**
   * <code>string productIndivNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIndivNoBytes();
}
