// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2_shipping.proto

package s2.shipping;

public interface updateLocResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shipping.updateLocResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locationNo = 1;</code>
   */
  java.lang.String getLocationNo();
  /**
   * <code>string locationNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationNoBytes();

  /**
   * <code>int32 availNum = 2;</code>
   */
  int getAvailNum();
}
