// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 3_inventory.proto

package s3.inventory;

public interface InventoryQtyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.InventoryQtyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();
}
