// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 3_inventory.proto

package s3.inventory;

public interface OrderHisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.OrderHisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>int32 totalQty = 2;</code>
   */
  int getTotalQty();

  /**
   * <code>float totalPrice = 3;</code>
   */
  float getTotalPrice();
}
