// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 3_inventory.proto

package s3.inventory;

public interface OrderHisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.OrderHisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 2;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
