// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1_receiving.proto

package s1.receiving;

public interface LocationAvailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:receiving.LocationAvailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 availNum = 1;</code>
   */
  int getAvailNum();
}
