// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1_receiving.proto

package s1.receiving;

public final class ReceivingImpl {
  private ReceivingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_ReceivedQtyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_ReceivedQtyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_ReceivedQtyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_ReceivedQtyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_SetLocRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_SetLocRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_SetLocResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_SetLocResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_LocationAvailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_LocationAvailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiving_LocationAvailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiving_LocationAvailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0211_receiving.proto\022\treceiving\"<\n\022Receiv" +
      "edQtyRequest\022\021\n\tproductNo\030\001 \001(\t\022\023\n\013recei" +
      "vedQty\030\002 \001(\005\"&\n\023ReceivedQtyResponse\022\017\n\007m" +
      "essage\030\001 \001(\t\":\n\rSetLocRequest\022\021\n\tproduct" +
      "No\030\001 \001(\t\022\026\n\016productIndivNo\030\002 \001(\t\"<\n\016SetL" +
      "ocResponse\022\026\n\016productIndivNo\030\001 \001(\t\022\022\n\nlo" +
      "cationNo\030\002 \001(\t\"*\n\024LocationAvailRequest\022\022" +
      "\n\nlocationNo\030\001 \001(\t\")\n\025LocationAvailRespo" +
      "nse\022\020\n\010availNum\030\001 \001(\0052\223\002\n\tReceiving\022Z\n\025c" +
      "heckReceivedQuantity\022\035.receiving.Receive" +
      "dQtyRequest\032\036.receiving.ReceivedQtyRespo" +
      "nse\"\000(\001\022H\n\013setLocation\022\030.receiving.SetLo" +
      "cRequest\032\031.receiving.SetLocResponse\"\000(\0010" +
      "\001\022`\n\031checkLocationAvailability\022\037.receivi" +
      "ng.LocationAvailRequest\032 .receiving.Loca" +
      "tionAvailResponse\"\000B\037\n\014s1.receivingB\rRec" +
      "eivingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_receiving_ReceivedQtyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_receiving_ReceivedQtyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_ReceivedQtyRequest_descriptor,
        new java.lang.String[] { "ProductNo", "ReceivedQty", });
    internal_static_receiving_ReceivedQtyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_receiving_ReceivedQtyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_ReceivedQtyResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_receiving_SetLocRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_receiving_SetLocRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_SetLocRequest_descriptor,
        new java.lang.String[] { "ProductNo", "ProductIndivNo", });
    internal_static_receiving_SetLocResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_receiving_SetLocResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_SetLocResponse_descriptor,
        new java.lang.String[] { "ProductIndivNo", "LocationNo", });
    internal_static_receiving_LocationAvailRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_receiving_LocationAvailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_LocationAvailRequest_descriptor,
        new java.lang.String[] { "LocationNo", });
    internal_static_receiving_LocationAvailResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_receiving_LocationAvailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiving_LocationAvailResponse_descriptor,
        new java.lang.String[] { "AvailNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
