// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1_receiving.proto

package s1.receiving;

public interface ReceivedQtyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:receiving.ReceivedQtyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>int32 receivedQty = 2;</code>
   */
  int getReceivedQty();
}
