// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1_receiving.proto

package s1.receiving;

public interface SetLocResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:receiving.SetLocResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productIndivNo = 1;</code>
   */
  java.lang.String getProductIndivNo();
  /**
   * <code>string productIndivNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIndivNoBytes();

  /**
   * <code>string locationNo = 2;</code>
   */
  java.lang.String getLocationNo();
  /**
   * <code>string locationNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationNoBytes();
}
