// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1_receiving.proto

package s1.receiving;

public interface SetLocRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:receiving.SetLocRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>string productIndivNo = 2;</code>
   */
  java.lang.String getProductIndivNo();
  /**
   * <code>string productIndivNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductIndivNoBytes();
}
